import { generateMarkdownReport } from "../src/utils/reportGenerator.js";

describe("Report Generator", () => {
  test("generates markdown report with correct structure", () => {
    const results = {
      platform: "Facebook",
      score: 72,
      checklist: [
        { text: "Profile picture uploaded", completed: true },
        { text: "Verified badge applied", completed: false }
      ]
    };

    const report = generateMarkdownReport(results);

    // Basic structure checks
    expect(report).toContain("# 📊 Digital Marketing Audit Report");
    expect(report).toContain("## Platform: Facebook");
    expect(report).toContain("**Score:** 72/100");
    expect(report).toContain("Checklist Results");

    // Checklist items
    expect(report).toContain("✅ Profile picture uploaded");
    expect(report).toContain("❌ Verified badge applied");

    // Footer
    expect(report).toContain("Generated by Digital Marketing Checklist Plugin");
  });

  test("handles empty checklist gracefully", () => {
    const results = {
      platform: "Instagram",
      score: 40,
      checklist: []
    };

    const report = generateMarkdownReport(results);

    expect(report).toContain("## Platform: Instagram");
    expect(report).toContain("**Score:** 40/100");
    expect(report).toContain("Checklist Results");
  });
});
