/**
 * Report Generator
 * Converts audit results into Markdown content for export.
 */

import { getRating } from "./scoring";

/**
 * Generate Markdown report
 * @param {Object} results - Audit results
 * Example:
 * {
 *   platform: "Facebook",
 *   score: 72,
 *   checklist: [
 *     { text: "Profile picture uploaded", completed: true },
 *     { text: "Verified badge applied", completed: false }
 *   ]
 * }
 * @returns {String} Markdown report
 */
export function generateMarkdownReport(results) {
  const { platform, score, checklist } = results;
  const rating = getRating(score);

  let md = `# 📊 Digital Marketing Audit Report\n\n`;
  md += `## Platform: ${platform}\n`;
  md += `**Score:** ${score}/100 (${rating})\n\n`;

  md += `### Checklist Results\n`;
  checklist.forEach((item) => {
    const status = item.completed ? "✅" : "❌";
    md += `- ${status} ${item.text}\n`;
  });

  md += `\n---\nGenerated by Digital Marketing Checklist Plugin\n`;

  return md;
}

/**
 * Example usage:
 * const report = generateMarkdownReport({
 *   platform: "Facebook",
 *   score: 72,
 *   checklist: [
 *     { text: "Profile picture uploaded", completed: true },
 *     { text: "Verified badge applied", completed: false }
 *   ]
 * });
 * console.log(report);
 */
